// 应用URL数据库 - 200+ 常见服务
const APP_DATABASE = {
    // ===== 效率工具 =====
    'notion': { name: 'Notion', login: 'https://www.notion.so/login', settings: 'https://www.notion.so/my-account', security: 'https://www.notion.so/my-account/security' },
    'trello': { name: 'Trello', login: 'https://trello.com/login', settings: 'https://trello.com/your-profile', security: 'https://id.atlassian.com/manage-profile/security' },
    'asana': { name: 'Asana', login: 'https://app.asana.com/-/login', settings: 'https://app.asana.com/0/my-settings/profile', security: 'https://app.asana.com/0/my-settings/account' },
    'slack': { name: 'Slack', login: 'https://slack.com/signin', settings: 'https://slack.com/account/settings', security: 'https://slack.com/account/settings#security' },
    'evernote': { name: 'Evernote', login: 'https://www.evernote.com/Login.action', settings: 'https://www.evernote.com/Settings.action', security: 'https://www.evernote.com/SecuritySettings.action' },
    'monday': { name: 'Monday.com', login: 'https://auth.monday.com/login', settings: 'https://auth.monday.com/my-profile', security: null },
    'miro': { name: 'Miro', login: 'https://miro.com/login/', settings: 'https://miro.com/app/settings/user-profile/', security: 'https://miro.com/app/settings/user-profile/security/' },
    'airtable': { name: 'Airtable', login: 'https://airtable.com/login', settings: 'https://airtable.com/account', security: null },
    'clickup': { name: 'ClickUp', login: 'https://app.clickup.com/login', settings: 'https://app.clickup.com/settings/profile', security: null },
    'todoist': { name: 'Todoist', login: 'https://todoist.com/users/showlogin', settings: 'https://todoist.com/app/settings/account', security: null },
    'ticktick': { name: 'TickTick', login: 'https://ticktick.com/signin', settings: 'https://ticktick.com/webapp/#settings/account', security: null },
    'basecamp': { name: 'Basecamp', login: 'https://launchpad.37signals.com/signin', settings: 'https://launchpad.37signals.com/profile', security: null },
    'wrike': { name: 'Wrike', login: 'https://login.wrike.com/login/', settings: 'https://www.wrike.com/workspace.htm#path=account', security: null },
    'smartsheet': { name: 'Smartsheet', login: 'https://app.smartsheet.com/b/home', settings: 'https://app.smartsheet.com/b/home?settings', security: null },
    'coda': { name: 'Coda', login: 'https://coda.io/signin', settings: 'https://coda.io/account', security: null },

    // ===== 设计工具 =====
    'figma': { name: 'Figma', login: 'https://www.figma.com/login', settings: 'https://www.figma.com/settings', security: 'https://www.figma.com/settings#security' },
    'canva': { name: 'Canva', login: 'https://www.canva.com/login', settings: 'https://www.canva.com/settings/account', security: 'https://www.canva.com/settings/login-security' },
    'adobe': { name: 'Adobe', login: 'https://account.adobe.com/sign-in', settings: 'https://account.adobe.com/profile', security: 'https://account.adobe.com/security' },
    'sketch': { name: 'Sketch', login: 'https://www.sketch.com/signin/', settings: 'https://www.sketch.com/settings/', security: null },
    'invision': { name: 'InVision', login: 'https://projects.invisionapp.com/d/login', settings: 'https://projects.invisionapp.com/d/#/account', security: null },
    'zeplin': { name: 'Zeplin', login: 'https://app.zeplin.io/login', settings: 'https://app.zeplin.io/profile', security: null },
    'framer': { name: 'Framer', login: 'https://framer.com/login/', settings: 'https://framer.com/account/', security: null },
    'dribbble': { name: 'Dribbble', login: 'https://dribbble.com/session/new', settings: 'https://dribbble.com/account', security: 'https://dribbble.com/account/password' },
    'behance': { name: 'Behance', login: 'https://www.behance.net/login', settings: 'https://www.behance.net/settings', security: null },
    'unsplash': { name: 'Unsplash', login: 'https://unsplash.com/login', settings: 'https://unsplash.com/account', security: null },
    'pexels': { name: 'Pexels', login: 'https://www.pexels.com/login/', settings: 'https://www.pexels.com/settings/', security: null },
    'pixlr': { name: 'Pixlr', login: 'https://pixlr.com/myaccount/', settings: 'https://pixlr.com/myaccount/', security: null },
    'photopea': { name: 'Photopea', login: 'https://www.photopea.com/', settings: null, security: null },
    'lucidchart': { name: 'Lucidchart', login: 'https://lucid.app/users/login', settings: 'https://lucid.app/users/settings', security: null },
    'whimsical': { name: 'Whimsical', login: 'https://whimsical.com/login', settings: 'https://whimsical.com/settings', security: null },

    // ===== 开发工具 =====
    'github': { name: 'GitHub', login: 'https://github.com/login', settings: 'https://github.com/settings/profile', security: 'https://github.com/settings/security' },
    'gitlab': { name: 'GitLab', login: 'https://gitlab.com/users/sign_in', settings: 'https://gitlab.com/-/profile', security: 'https://gitlab.com/-/profile/password/edit' },
    'bitbucket': { name: 'Bitbucket', login: 'https://bitbucket.org/account/signin/', settings: 'https://bitbucket.org/account/settings/', security: 'https://id.atlassian.com/manage-profile/security' },
    'vercel': { name: 'Vercel', login: 'https://vercel.com/login', settings: 'https://vercel.com/account', security: 'https://vercel.com/account/security' },
    'netlify': { name: 'Netlify', login: 'https://app.netlify.com/login', settings: 'https://app.netlify.com/user/settings', security: null },
    'heroku': { name: 'Heroku', login: 'https://id.heroku.com/login', settings: 'https://dashboard.heroku.com/account', security: null },
    'replit': { name: 'Replit', login: 'https://replit.com/login', settings: 'https://replit.com/account', security: null },
    'codepen': { name: 'CodePen', login: 'https://codepen.io/login', settings: 'https://codepen.io/your-settings', security: 'https://codepen.io/your-settings/security' },
    'codesandbox': { name: 'CodeSandbox', login: 'https://codesandbox.io/signin', settings: 'https://codesandbox.io/dashboard/settings', security: null },
    'stackoverflow': { name: 'Stack Overflow', login: 'https://stackoverflow.com/users/login', settings: 'https://stackoverflow.com/users/edit/current', security: 'https://stackoverflow.com/users/edit/current?tab=logins' },
    'jsfiddle': { name: 'JSFiddle', login: 'https://jsfiddle.net/user/login/', settings: 'https://jsfiddle.net/user/settings/', security: null },
    'glitch': { name: 'Glitch', login: 'https://glitch.com/signin', settings: 'https://glitch.com/settings', security: null },
    'npm': { name: 'npm', login: 'https://www.npmjs.com/login', settings: 'https://www.npmjs.com/settings/', security: null },
    'docker': { name: 'Docker Hub', login: 'https://hub.docker.com/login', settings: 'https://hub.docker.com/settings/general', security: 'https://hub.docker.com/settings/security' },
    'digitalocean': { name: 'DigitalOcean', login: 'https://cloud.digitalocean.com/login', settings: 'https://cloud.digitalocean.com/account/profile', security: 'https://cloud.digitalocean.com/account/security' },
    'aws': { name: 'AWS', login: 'https://signin.aws.amazon.com/', settings: 'https://console.aws.amazon.com/iam/home', security: null },
    'azure': { name: 'Azure', login: 'https://portal.azure.com/', settings: 'https://portal.azure.com/#settings', security: null },
    'gcp': { name: 'Google Cloud', login: 'https://console.cloud.google.com/', settings: 'https://console.cloud.google.com/iam-admin', security: null },
    'firebase': { name: 'Firebase', login: 'https://console.firebase.google.com/', settings: 'https://console.firebase.google.com/project/_/settings', security: null },
    'supabase': { name: 'Supabase', login: 'https://app.supabase.com/sign-in', settings: 'https://app.supabase.com/account/me', security: null },
    'planetscale': { name: 'PlanetScale', login: 'https://auth.planetscale.com/sign-in', settings: 'https://app.planetscale.com/settings', security: null },
    'railway': { name: 'Railway', login: 'https://railway.app/login', settings: 'https://railway.app/account', security: null },
    'render': { name: 'Render', login: 'https://dashboard.render.com/login', settings: 'https://dashboard.render.com/settings', security: null },
    'fly': { name: 'Fly.io', login: 'https://fly.io/app/sign-in', settings: 'https://fly.io/user/personal_access_tokens', security: null },
    'cloudflare': { name: 'Cloudflare', login: 'https://dash.cloudflare.com/login', settings: 'https://dash.cloudflare.com/profile', security: 'https://dash.cloudflare.com/profile/authentication' },
    'sentry': { name: 'Sentry', login: 'https://sentry.io/auth/login/', settings: 'https://sentry.io/settings/account/details/', security: 'https://sentry.io/settings/account/security/' },
    'datadog': { name: 'Datadog', login: 'https://app.datadoghq.com/account/login', settings: 'https://app.datadoghq.com/personal-settings', security: null },
    'newrelic': { name: 'New Relic', login: 'https://login.newrelic.com/login', settings: 'https://one.newrelic.com/account-settings', security: null },
    'postman': { name: 'Postman', login: 'https://identity.getpostman.com/login', settings: 'https://web.postman.co/settings/me', security: null },
    'insomnia': { name: 'Insomnia', login: 'https://app.insomnia.rest/app/authorize', settings: 'https://app.insomnia.rest/app/settings', security: null },
    'jira': { name: 'Jira', login: 'https://id.atlassian.com/login', settings: 'https://id.atlassian.com/manage-profile', security: 'https://id.atlassian.com/manage-profile/security' },
    'confluence': { name: 'Confluence', login: 'https://id.atlassian.com/login', settings: 'https://id.atlassian.com/manage-profile', security: 'https://id.atlassian.com/manage-profile/security' },
    'linear': { name: 'Linear', login: 'https://linear.app/login', settings: 'https://linear.app/settings/account', security: null },
    'hashnode': { name: 'Hashnode', login: 'https://hashnode.com/onboard', settings: 'https://hashnode.com/settings', security: null },
    'devto': { name: 'DEV.to', login: 'https://dev.to/enter', settings: 'https://dev.to/settings', security: null },

    // ===== 社交/通讯 =====
    'discord': { name: 'Discord', login: 'https://discord.com/login', settings: 'https://discord.com/channels/@me', security: 'https://discord.com/settings/account' },
    'twitter': { name: 'Twitter/X', login: 'https://twitter.com/login', settings: 'https://twitter.com/settings/profile', security: 'https://twitter.com/settings/account' },
    'x': { name: 'X (Twitter)', login: 'https://x.com/login', settings: 'https://x.com/settings/profile', security: 'https://x.com/settings/account' },
    'linkedin': { name: 'LinkedIn', login: 'https://www.linkedin.com/login', settings: 'https://www.linkedin.com/mypreferences/d/account-preferences', security: 'https://www.linkedin.com/psettings/sign-in-and-security' },
    'reddit': { name: 'Reddit', login: 'https://www.reddit.com/login/', settings: 'https://www.reddit.com/settings/account', security: 'https://www.reddit.com/settings/account' },
    'pinterest': { name: 'Pinterest', login: 'https://www.pinterest.com/login/', settings: 'https://www.pinterest.com/settings/edit-profile/', security: 'https://www.pinterest.com/settings/account-settings/' },
    'quora': { name: 'Quora', login: 'https://www.quora.com/', settings: 'https://www.quora.com/settings', security: null },
    'medium': { name: 'Medium', login: 'https://medium.com/m/signin', settings: 'https://medium.com/me/settings/account', security: 'https://medium.com/me/settings/security' },
    'tumblr': { name: 'Tumblr', login: 'https://www.tumblr.com/login', settings: 'https://www.tumblr.com/settings/account', security: null },
    'facebook': { name: 'Facebook', login: 'https://www.facebook.com/login', settings: 'https://www.facebook.com/settings', security: 'https://www.facebook.com/settings?tab=security' },
    'instagram': { name: 'Instagram', login: 'https://www.instagram.com/accounts/login/', settings: 'https://www.instagram.com/accounts/edit/', security: 'https://www.instagram.com/accounts/password/change/' },
    'tiktok': { name: 'TikTok', login: 'https://www.tiktok.com/login', settings: 'https://www.tiktok.com/setting', security: null },
    'snapchat': { name: 'Snapchat', login: 'https://accounts.snapchat.com/accounts/login', settings: 'https://accounts.snapchat.com/accounts/settings', security: null },
    'whatsapp': { name: 'WhatsApp', login: 'https://web.whatsapp.com/', settings: null, security: null },
    'telegram': { name: 'Telegram', login: 'https://web.telegram.org/', settings: 'https://my.telegram.org/', security: null },
    'signal': { name: 'Signal', login: null, settings: null, security: null },
    'wechat': { name: 'WeChat', login: 'https://web.wechat.com/', settings: null, security: null },
    'line': { name: 'LINE', login: 'https://account.line.biz/login', settings: 'https://account.line.biz/settings', security: null },
    'viber': { name: 'Viber', login: null, settings: null, security: null },
    'mastodon': { name: 'Mastodon', login: 'https://mastodon.social/auth/sign_in', settings: 'https://mastodon.social/settings/profile', security: 'https://mastodon.social/auth/edit' },
    'bluesky': { name: 'Bluesky', login: 'https://bsky.app/', settings: 'https://bsky.app/settings', security: null },
    'threads': { name: 'Threads', login: 'https://www.threads.net/login', settings: 'https://www.threads.net/settings', security: null },

    // ===== 娱乐 =====
    'spotify': { name: 'Spotify', login: 'https://accounts.spotify.com/login', settings: 'https://www.spotify.com/account/overview/', security: 'https://www.spotify.com/account/set-device-password/' },
    'netflix': { name: 'Netflix', login: 'https://www.netflix.com/login', settings: 'https://www.netflix.com/YourAccount', security: 'https://www.netflix.com/password' },
    'youtube': { name: 'YouTube', login: 'https://accounts.google.com/', settings: 'https://www.youtube.com/account', security: 'https://myaccount.google.com/security' },
    'twitch': { name: 'Twitch', login: 'https://www.twitch.tv/login', settings: 'https://www.twitch.tv/settings/profile', security: 'https://www.twitch.tv/settings/security' },
    'steam': { name: 'Steam', login: 'https://store.steampowered.com/login/', settings: 'https://store.steampowered.com/account/', security: 'https://store.steampowered.com/account/security' },
    'epicgames': { name: 'Epic Games', login: 'https://www.epicgames.com/id/login', settings: 'https://www.epicgames.com/account/personal', security: 'https://www.epicgames.com/account/password' },
    'playstation': { name: 'PlayStation', login: 'https://my.playstation.com/sign-in', settings: 'https://my.playstation.com/', security: 'https://id.sonyentertainmentnetwork.com/signin/' },
    'xbox': { name: 'Xbox', login: 'https://login.live.com/', settings: 'https://account.xbox.com/profile', security: 'https://account.microsoft.com/security' },
    'nintendo': { name: 'Nintendo', login: 'https://accounts.nintendo.com/', settings: 'https://accounts.nintendo.com/profile/edit', security: 'https://accounts.nintendo.com/security' },
    'roblox': { name: 'Roblox', login: 'https://www.roblox.com/login', settings: 'https://www.roblox.com/my/account', security: 'https://www.roblox.com/my/account#!/security' },
    'minecraft': { name: 'Minecraft', login: 'https://www.minecraft.net/login', settings: 'https://www.minecraft.net/profile', security: null },
    'ea': { name: 'EA/Origin', login: 'https://www.ea.com/login', settings: 'https://myaccount.ea.com/cp-ui/aboutme/index', security: 'https://myaccount.ea.com/cp-ui/security/index' },
    'ubisoft': { name: 'Ubisoft', login: 'https://connect.ubisoft.com/login', settings: 'https://account.ubisoft.com/account-information', security: 'https://account.ubisoft.com/security-settings' },
    'blizzard': { name: 'Blizzard', login: 'https://battle.net/login/', settings: 'https://account.battle.net/details', security: 'https://account.battle.net/security' },
    'gog': { name: 'GOG', login: 'https://login.gog.com/', settings: 'https://www.gog.com/account', security: 'https://www.gog.com/account/settings/security' },
    'humblebundle': { name: 'Humble Bundle', login: 'https://www.humblebundle.com/login', settings: 'https://www.humblebundle.com/user/settings', security: null },
    'itch': { name: 'itch.io', login: 'https://itch.io/login', settings: 'https://itch.io/user/settings', security: null },
    'primevideo': { name: 'Prime Video', login: 'https://www.primevideo.com/', settings: 'https://www.amazon.com/gp/css/homepage.html', security: 'https://www.amazon.com/a/settings/approval' },
    'hulu': { name: 'Hulu', login: 'https://secure.hulu.com/login', settings: 'https://secure.hulu.com/account', security: 'https://secure.hulu.com/account/password' },
    'disneyplus': { name: 'Disney+', login: 'https://www.disneyplus.com/login', settings: 'https://www.disneyplus.com/account/profile', security: 'https://www.disneyplus.com/account/password' },
    'hbomax': { name: 'HBO Max', login: 'https://play.max.com/sign-in', settings: 'https://play.max.com/settings', security: null },
    'applemusic': { name: 'Apple Music', login: 'https://music.apple.com/', settings: 'https://appleid.apple.com/account/manage', security: null },
    'deezer': { name: 'Deezer', login: 'https://www.deezer.com/login', settings: 'https://www.deezer.com/account', security: null },
    'tidal': { name: 'Tidal', login: 'https://login.tidal.com/', settings: 'https://account.tidal.com/', security: null },
    'soundcloud': { name: 'SoundCloud', login: 'https://soundcloud.com/signin', settings: 'https://soundcloud.com/settings', security: null },
    'bandcamp': { name: 'Bandcamp', login: 'https://bandcamp.com/login', settings: 'https://bandcamp.com/settings', security: null },
    'crunchyroll': { name: 'Crunchyroll', login: 'https://www.crunchyroll.com/login', settings: 'https://www.crunchyroll.com/account', security: null },
    'funimation': { name: 'Funimation', login: 'https://www.funimation.com/log-in/', settings: 'https://www.funimation.com/account/', security: null },
    'bilibili': { name: 'Bilibili', login: 'https://passport.bilibili.com/login', settings: 'https://account.bilibili.com/account/home', security: 'https://passport.bilibili.com/account/security' },
    'niconico': { name: 'Niconico', login: 'https://account.nicovideo.jp/login', settings: 'https://account.nicovideo.jp/my/account', security: null },
    'vimeo': { name: 'Vimeo', login: 'https://vimeo.com/log_in', settings: 'https://vimeo.com/settings', security: 'https://vimeo.com/settings/account/password' },
    'dailymotion': { name: 'Dailymotion', login: 'https://www.dailymotion.com/signin', settings: 'https://www.dailymotion.com/settings', security: null },

    // ===== 购物/服务 =====
    'amazon': { name: 'Amazon', login: 'https://www.amazon.com/ap/signin', settings: 'https://www.amazon.com/gp/css/homepage.html', security: 'https://www.amazon.com/a/settings' },
    'ebay': { name: 'eBay', login: 'https://signin.ebay.com/signin/', settings: 'https://accountsettings.ebay.com/', security: 'https://accounts.ebay.com/acctsec/security-center' },
    'etsy': { name: 'Etsy', login: 'https://www.etsy.com/signin', settings: 'https://www.etsy.com/your/account', security: 'https://www.etsy.com/your/account/security' },
    'shopify': { name: 'Shopify', login: 'https://accounts.shopify.com/lookup', settings: 'https://accounts.shopify.com/', security: null },
    'wish': { name: 'Wish', login: 'https://www.wish.com/login', settings: 'https://www.wish.com/settings', security: null },
    'aliexpress': { name: 'AliExpress', login: 'https://login.aliexpress.com/', settings: 'https://www.aliexpress.com/p/account/index.html', security: null },
    'taobao': { name: 'Taobao', login: 'https://login.taobao.com/', settings: 'https://member1.taobao.com/member/fresh/account_management.htm', security: null },
    'jd': { name: 'JD.com', login: 'https://passport.jd.com/new/login.aspx', settings: 'https://safe.jd.com/user/paymentpassword/safetyCenter.action', security: null },
    'rakuten': { name: 'Rakuten', login: 'https://grp02.id.rakuten.co.jp/rms/nid/login', settings: 'https://member.id.rakuten.co.jp/rms/nid/menufwd', security: null },
    'walmart': { name: 'Walmart', login: 'https://www.walmart.com/account/login', settings: 'https://www.walmart.com/account/profile', security: null },
    'target': { name: 'Target', login: 'https://www.target.com/account', settings: 'https://www.target.com/account', security: null },
    'bestbuy': { name: 'Best Buy', login: 'https://www.bestbuy.com/identity/signin', settings: 'https://www.bestbuy.com/profile/c/details', security: null },
    'costco': { name: 'Costco', login: 'https://www.costco.com/LogonForm', settings: 'https://www.costco.com/MyAccountMainView', security: null },
    'ikea': { name: 'IKEA', login: 'https://www.ikea.com/jp/en/profile/login/', settings: 'https://www.ikea.com/jp/en/profile/', security: null },
    'airbnb': { name: 'Airbnb', login: 'https://www.airbnb.com/login', settings: 'https://www.airbnb.com/account-settings', security: 'https://www.airbnb.com/account-settings/login-and-security' },
    'uber': { name: 'Uber', login: 'https://auth.uber.com/login/', settings: 'https://riders.uber.com/settings', security: null },
    'lyft': { name: 'Lyft', login: 'https://www.lyft.com/login', settings: 'https://www.lyft.com/rider/account', security: null },
    'grab': { name: 'Grab', login: 'https://www.grab.com/', settings: 'https://www.grab.com/sg/profile/', security: null },
    'booking': { name: 'Booking.com', login: 'https://account.booking.com/sign-in', settings: 'https://account.booking.com/', security: 'https://account.booking.com/mysettings/security' },
    'expedia': { name: 'Expedia', login: 'https://www.expedia.com/user/signin', settings: 'https://www.expedia.com/user/account', security: null },
    'tripadvisor': { name: 'TripAdvisor', login: 'https://www.tripadvisor.com/RegistrationController', settings: 'https://www.tripadvisor.com/Settings', security: null },
    'doordash': { name: 'DoorDash', login: 'https://identity.doordash.com/auth', settings: 'https://www.doordash.com/consumer/account/', security: null },
    'ubereats': { name: 'Uber Eats', login: 'https://auth.uber.com/login/', settings: 'https://www.ubereats.com/account', security: null },
    'grubhub': { name: 'Grubhub', login: 'https://www.grubhub.com/login', settings: 'https://www.grubhub.com/account', security: null },
    'instacart': { name: 'Instacart', login: 'https://www.instacart.com/login', settings: 'https://www.instacart.com/store/account', security: null },

    // ===== 云存储 =====
    'dropbox': { name: 'Dropbox', login: 'https://www.dropbox.com/login', settings: 'https://www.dropbox.com/account', security: 'https://www.dropbox.com/account/security' },
    'box': { name: 'Box', login: 'https://app.box.com/login', settings: 'https://app.box.com/account', security: null },
    'mega': { name: 'MEGA', login: 'https://mega.io/login', settings: 'https://mega.io/fm/account', security: null },
    'onedrive': { name: 'OneDrive', login: 'https://onedrive.live.com/login/', settings: 'https://account.microsoft.com/', security: 'https://account.microsoft.com/security' },
    'icloud': { name: 'iCloud', login: 'https://www.icloud.com/', settings: 'https://appleid.apple.com/account/manage', security: null },
    'pcloud': { name: 'pCloud', login: 'https://my.pcloud.com/', settings: 'https://my.pcloud.com/#page=settings', security: null },
    'sync': { name: 'Sync.com', login: 'https://cp.sync.com/login/', settings: 'https://cp.sync.com/account/', security: null },
    'tresorit': { name: 'Tresorit', login: 'https://web.tresorit.com/', settings: 'https://tresorit.com/management/', security: null },
    'googledrive': { name: 'Google Drive', login: 'https://drive.google.com/', settings: 'https://myaccount.google.com/', security: 'https://myaccount.google.com/security' },

    // ===== 学习 =====
    'coursera': { name: 'Coursera', login: 'https://www.coursera.org/?authMode=login', settings: 'https://www.coursera.org/account-settings', security: null },
    'udemy': { name: 'Udemy', login: 'https://www.udemy.com/join/login-popup/', settings: 'https://www.udemy.com/user/edit-account/', security: null },
    'duolingo': { name: 'Duolingo', login: 'https://www.duolingo.com/', settings: 'https://www.duolingo.com/settings/account', security: null },
    'grammarly': { name: 'Grammarly', login: 'https://www.grammarly.com/signin', settings: 'https://account.grammarly.com/account', security: 'https://account.grammarly.com/security' },
    'edx': { name: 'edX', login: 'https://courses.edx.org/login', settings: 'https://courses.edx.org/account/settings', security: null },
    'udacity': { name: 'Udacity', login: 'https://auth.udacity.com/sign-in', settings: 'https://classroom.udacity.com/settings', security: null },
    'skillshare': { name: 'Skillshare', login: 'https://www.skillshare.com/login', settings: 'https://www.skillshare.com/settings', security: null },
    'linkedin learning': { name: 'LinkedIn Learning', login: 'https://www.linkedin.com/learning/', settings: 'https://www.linkedin.com/learning/me/settings', security: null },
    'pluralsight': { name: 'Pluralsight', login: 'https://app.pluralsight.com/id/', settings: 'https://app.pluralsight.com/id/account', security: null },
    'codecademy': { name: 'Codecademy', login: 'https://www.codecademy.com/login', settings: 'https://www.codecademy.com/account', security: null },
    'freecodecamp': { name: 'freeCodeCamp', login: 'https://www.freecodecamp.org/signin', settings: 'https://www.freecodecamp.org/settings', security: null },
    'khanacademy': { name: 'Khan Academy', login: 'https://www.khanacademy.org/login', settings: 'https://www.khanacademy.org/settings/account', security: null },
    'memrise': { name: 'Memrise', login: 'https://app.memrise.com/signin', settings: 'https://app.memrise.com/settings', security: null },
    'busuu': { name: 'Busuu', login: 'https://www.busuu.com/login', settings: 'https://www.busuu.com/dashboard/settings', security: null },
    'babbel': { name: 'Babbel', login: 'https://my.babbel.com/auth/login', settings: 'https://my.babbel.com/account', security: null },
    'rosettastone': { name: 'Rosetta Stone', login: 'https://www.rosettastone.com/', settings: 'https://totale.rosettastone.com/account', security: null },
    'cambly': { name: 'Cambly', login: 'https://www.cambly.com/login', settings: 'https://www.cambly.com/account', security: null },
    'italki': { name: 'italki', login: 'https://www.italki.com/login', settings: 'https://www.italki.com/settings', security: null },
    'quizlet': { name: 'Quizlet', login: 'https://quizlet.com/login', settings: 'https://quizlet.com/settings', security: null },
    'anki': { name: 'AnkiWeb', login: 'https://ankiweb.net/account/login', settings: 'https://ankiweb.net/account', security: null },

    // ===== 金融/加密 =====
    'paypal': { name: 'PayPal', login: 'https://www.paypal.com/signin', settings: 'https://www.paypal.com/myaccount/settings/', security: 'https://www.paypal.com/myaccount/settings/security/' },
    'stripe': { name: 'Stripe', login: 'https://dashboard.stripe.com/login', settings: 'https://dashboard.stripe.com/settings/account', security: null },
    'coinbase': { name: 'Coinbase', login: 'https://www.coinbase.com/signin', settings: 'https://www.coinbase.com/settings', security: 'https://www.coinbase.com/settings/security' },
    'binance': { name: 'Binance', login: 'https://accounts.binance.com/login', settings: 'https://www.binance.com/my/dashboard', security: 'https://www.binance.com/my/security' },
    'kraken': { name: 'Kraken', login: 'https://www.kraken.com/sign-in', settings: 'https://www.kraken.com/u/settings', security: 'https://www.kraken.com/u/security' },
    'gemini': { name: 'Gemini Exchange', login: 'https://exchange.gemini.com/signin', settings: 'https://exchange.gemini.com/settings', security: 'https://exchange.gemini.com/settings/security' },
    'ftx': { name: 'FTX', login: 'https://ftx.com/login', settings: 'https://ftx.com/settings', security: null },
    'kucoin': { name: 'KuCoin', login: 'https://www.kucoin.com/login', settings: 'https://www.kucoin.com/account/security', security: 'https://www.kucoin.com/account/security' },
    'bybit': { name: 'Bybit', login: 'https://www.bybit.com/login', settings: 'https://www.bybit.com/user/accounts', security: 'https://www.bybit.com/user/accounts/security' },
    'okx': { name: 'OKX', login: 'https://www.okx.com/account/login', settings: 'https://www.okx.com/account', security: 'https://www.okx.com/account/security' },
    'robinhood': { name: 'Robinhood', login: 'https://robinhood.com/login', settings: 'https://robinhood.com/account/settings', security: 'https://robinhood.com/account/settings' },
    'etrade': { name: 'E*TRADE', login: 'https://us.etrade.com/e/t/user/login', settings: 'https://us.etrade.com/etx/pxy/my-profile', security: null },
    'fidelity': { name: 'Fidelity', login: 'https://digital.fidelity.com/prgw/digital/login/full-page', settings: 'https://digital.fidelity.com/ftgw/digital/profile/', security: null },
    'schwab': { name: 'Schwab', login: 'https://client.schwab.com/Login/SignOn', settings: 'https://client.schwab.com/clientapps/accounts/profile', security: null },
    'venmo': { name: 'Venmo', login: 'https://venmo.com/account/sign-in', settings: 'https://venmo.com/account/settings', security: null },
    'cashapp': { name: 'Cash App', login: 'https://cash.app/login', settings: 'https://cash.app/account', security: null },
    'wise': { name: 'Wise', login: 'https://wise.com/login/', settings: 'https://wise.com/user/account/', security: 'https://wise.com/user/account/security' },
    'revolut': { name: 'Revolut', login: 'https://app.revolut.com/start', settings: 'https://app.revolut.com/settings', security: null },
    'n26': { name: 'N26', login: 'https://app.n26.com/login', settings: 'https://app.n26.com/settings', security: null },
    'metamask': { name: 'MetaMask', login: null, settings: null, security: null },
    'phantom': { name: 'Phantom Wallet', login: null, settings: null, security: null },

    // ===== AI工具 =====
    'chatgpt': { name: 'ChatGPT', login: 'https://chat.openai.com/auth/login', settings: 'https://chat.openai.com/settings', security: null },
    'openai': { name: 'OpenAI', login: 'https://platform.openai.com/login', settings: 'https://platform.openai.com/account', security: null },
    'claude': { name: 'Claude AI', login: 'https://claude.ai/login', settings: 'https://claude.ai/settings', security: null },
    'anthropic': { name: 'Anthropic', login: 'https://console.anthropic.com/login', settings: 'https://console.anthropic.com/settings', security: null },
    'midjourney': { name: 'Midjourney', login: 'https://www.midjourney.com/account/', settings: 'https://www.midjourney.com/account/', security: null },
    'dalle': { name: 'DALL-E', login: 'https://labs.openai.com/', settings: 'https://platform.openai.com/account', security: null },
    'stability': { name: 'Stability AI', login: 'https://platform.stability.ai/', settings: 'https://platform.stability.ai/account', security: null },
    'runway': { name: 'Runway', login: 'https://app.runwayml.com/', settings: 'https://app.runwayml.com/settings', security: null },
    'jasper': { name: 'Jasper AI', login: 'https://app.jasper.ai/login', settings: 'https://app.jasper.ai/settings', security: null },
    'copy': { name: 'Copy.ai', login: 'https://app.copy.ai/login', settings: 'https://app.copy.ai/settings', security: null },
    'writesonic': { name: 'Writesonic', login: 'https://writesonic.com/login', settings: 'https://writesonic.com/settings', security: null },
    'perplexity': { name: 'Perplexity AI', login: 'https://www.perplexity.ai/', settings: 'https://www.perplexity.ai/settings', security: null },
    'poe': { name: 'Poe', login: 'https://poe.com/login', settings: 'https://poe.com/settings', security: null },
    'character': { name: 'Character.AI', login: 'https://character.ai/login', settings: 'https://character.ai/settings', security: null },
    'replika': { name: 'Replika', login: 'https://my.replika.com/', settings: 'https://my.replika.com/settings', security: null },
    'notion ai': { name: 'Notion AI', login: 'https://www.notion.so/login', settings: 'https://www.notion.so/my-account', security: null },
    'otter': { name: 'Otter.ai', login: 'https://otter.ai/login', settings: 'https://otter.ai/account', security: null },
    'descript': { name: 'Descript', login: 'https://www.descript.com/login', settings: 'https://www.descript.com/settings', security: null },
    'synthesia': { name: 'Synthesia', login: 'https://app.synthesia.io/', settings: 'https://app.synthesia.io/settings', security: null },
    'elevenlabs': { name: 'ElevenLabs', login: 'https://elevenlabs.io/sign-in', settings: 'https://elevenlabs.io/settings', security: null },
    'huggingface': { name: 'Hugging Face', login: 'https://huggingface.co/login', settings: 'https://huggingface.co/settings/profile', security: 'https://huggingface.co/settings/account' },
    'cohere': { name: 'Cohere', login: 'https://dashboard.cohere.com/login', settings: 'https://dashboard.cohere.com/settings', security: null },
    'replicate': { name: 'Replicate', login: 'https://replicate.com/signin', settings: 'https://replicate.com/account', security: null },

    // ===== 视频会议 =====
    'zoom': { name: 'Zoom', login: 'https://zoom.us/signin', settings: 'https://zoom.us/profile', security: 'https://zoom.us/profile/setting' },
    'teams': { name: 'Microsoft Teams', login: 'https://teams.microsoft.com/', settings: 'https://myaccount.microsoft.com/', security: 'https://account.microsoft.com/security' },
    'meet': { name: 'Google Meet', login: 'https://meet.google.com/', settings: 'https://myaccount.google.com/', security: null },
    'webex': { name: 'Cisco Webex', login: 'https://signin.webex.com/', settings: 'https://settings.webex.com/', security: null },
    'skype': { name: 'Skype', login: 'https://login.skype.com/login', settings: 'https://account.live.com/', security: 'https://account.microsoft.com/security' },
    'gotomeeting': { name: 'GoToMeeting', login: 'https://authentication.logmeininc.com/login', settings: 'https://global.gotomeeting.com/meeting/settings', security: null },
    'whereby': { name: 'Whereby', login: 'https://whereby.com/user/login', settings: 'https://whereby.com/user/profile', security: null },
    'jitsi': { name: 'Jitsi', login: 'https://jaas.8x8.vc/', settings: null, security: null },
    'loom': { name: 'Loom', login: 'https://www.loom.com/login', settings: 'https://www.loom.com/my-account', security: null },
    'around': { name: 'Around', login: 'https://www.around.co/login', settings: 'https://www.around.co/settings', security: null },

    // ===== Microsoft/Office =====
    'microsoft': { name: 'Microsoft', login: 'https://login.microsoftonline.com/', settings: 'https://account.microsoft.com/', security: 'https://account.microsoft.com/security' },
    'office365': { name: 'Office 365', login: 'https://www.office.com/', settings: 'https://account.microsoft.com/', security: 'https://account.microsoft.com/security' },
    'outlook': { name: 'Outlook', login: 'https://outlook.live.com/owa/', settings: 'https://account.microsoft.com/', security: 'https://account.microsoft.com/security' },
    'onenote': { name: 'OneNote', login: 'https://www.onenote.com/', settings: 'https://account.microsoft.com/', security: null },
    'sharepoint': { name: 'SharePoint', login: 'https://login.microsoftonline.com/', settings: 'https://account.microsoft.com/', security: null },

    // ===== Google 相关 =====
    'google': { name: 'Google', login: 'https://accounts.google.com/', settings: 'https://myaccount.google.com/', security: 'https://myaccount.google.com/security' },
    'gmail': { name: 'Gmail', login: 'https://accounts.google.com/', settings: 'https://mail.google.com/mail/u/0/#settings', security: 'https://myaccount.google.com/security' },
    'googledocs': { name: 'Google Docs', login: 'https://docs.google.com/', settings: 'https://myaccount.google.com/', security: null },
    'googlesheets': { name: 'Google Sheets', login: 'https://sheets.google.com/', settings: 'https://myaccount.google.com/', security: null },
    'googleslides': { name: 'Google Slides', login: 'https://slides.google.com/', settings: 'https://myaccount.google.com/', security: null },
    'googlecalendar': { name: 'Google Calendar', login: 'https://calendar.google.com/', settings: 'https://calendar.google.com/calendar/r/settings', security: null },
    'googlephotos': { name: 'Google Photos', login: 'https://photos.google.com/', settings: 'https://myaccount.google.com/', security: null },
    'googlegemini': { name: 'Google Gemini', login: 'https://gemini.google.com/', settings: 'https://myaccount.google.com/', security: 'https://myaccount.google.com/security' },
    'google ai studio': { name: 'Google AI Studio', login: 'https://aistudio.google.com/', settings: 'https://myaccount.google.com/', security: null },
    'google antigravity': { name: 'Google Antigravity', login: null, settings: 'https://myaccount.google.com/', security: null },
    'gemini code assist': { name: 'Gemini Code Assist', login: 'https://cloud.google.com/', settings: 'https://myaccount.google.com/', security: null },

    // ===== 其他 =====
    'ricedrive': { name: 'RiceDrive', login: 'https://www.ricedrive.com/', settings: null, security: null },
    'zapier': { name: 'Zapier', login: 'https://zapier.com/app/login', settings: 'https://zapier.com/app/settings/profile', security: 'https://zapier.com/app/settings/security' },
    'ifttt': { name: 'IFTTT', login: 'https://ifttt.com/login', settings: 'https://ifttt.com/settings', security: null },
    'make': { name: 'Make (Integromat)', login: 'https://www.make.com/en/login', settings: 'https://www.make.com/en/user/profile', security: null },
    'n8n': { name: 'n8n', login: 'https://app.n8n.cloud/login', settings: 'https://app.n8n.cloud/settings', security: null },
    'calendly': { name: 'Calendly', login: 'https://calendly.com/login', settings: 'https://calendly.com/app/personal/profile', security: 'https://calendly.com/app/personal/security' },
    'acuity': { name: 'Acuity Scheduling', login: 'https://acuityscheduling.com/login', settings: 'https://acuityscheduling.com/login.php?action=settings', security: null },
    'doodle': { name: 'Doodle', login: 'https://doodle.com/login', settings: 'https://doodle.com/settings', security: null },
    'typeform': { name: 'Typeform', login: 'https://admin.typeform.com/login', settings: 'https://admin.typeform.com/account', security: 'https://admin.typeform.com/account#/section/security' },
    'surveymonkey': { name: 'SurveyMonkey', login: 'https://www.surveymonkey.com/user/sign-in/', settings: 'https://www.surveymonkey.com/user/account/', security: null },
    'googleforms': { name: 'Google Forms', login: 'https://docs.google.com/forms/', settings: 'https://myaccount.google.com/', security: null },
    'jotform': { name: 'JotForm', login: 'https://www.jotform.com/login/', settings: 'https://www.jotform.com/myaccount/', security: 'https://www.jotform.com/myaccount/security' },
    'adobesign': { name: 'Adobe Sign', login: 'https://secure.echosign.com/public/login', settings: 'https://secure.echosign.com/account/homeJS', security: null },
    'docusign': { name: 'DocuSign', login: 'https://account.docusign.com/', settings: 'https://account.docusign.com/', security: null },
    'hellosign': { name: 'HelloSign', login: 'https://app.hellosign.com/account/logIn', settings: 'https://app.hellosign.com/account', security: null },
    'mailchimp': { name: 'Mailchimp', login: 'https://login.mailchimp.com/', settings: 'https://us1.admin.mailchimp.com/account/', security: 'https://us1.admin.mailchimp.com/account/security/' },
    'convertkit': { name: 'ConvertKit', login: 'https://app.convertkit.com/users/login', settings: 'https://app.convertkit.com/account/edit', security: null },
    'hubspot': { name: 'HubSpot', login: 'https://app.hubspot.com/login/', settings: 'https://app.hubspot.com/settings/', security: null },
    'salesforce': { name: 'Salesforce', login: 'https://login.salesforce.com/', settings: 'https://login.salesforce.com/', security: null },
    'zendesk': { name: 'Zendesk', login: 'https://www.zendesk.com/login/', settings: 'https://support.zendesk.com/hc/admin/settings', security: null },
    'intercom': { name: 'Intercom', login: 'https://app.intercom.com/', settings: 'https://app.intercom.com/settings', security: null },
    'freshdesk': { name: 'Freshdesk', login: 'https://www.freshworks.com/login/', settings: 'https://www.freshworks.com/account/', security: null },
    'buffer': { name: 'Buffer', login: 'https://login.buffer.com/login', settings: 'https://account.buffer.com/', security: null },
    'hootsuite': { name: 'Hootsuite', login: 'https://hootsuite.com/login', settings: 'https://hootsuite.com/dashboard#/member/settings', security: null },
    'later': { name: 'Later', login: 'https://app.later.com/login', settings: 'https://app.later.com/account', security: null },
    'sproutsocial': { name: 'Sprout Social', login: 'https://app.sproutsocial.com/login/', settings: 'https://app.sproutsocial.com/settings/', security: null },
    '1password': { name: '1Password', login: 'https://my.1password.com/signin', settings: 'https://my.1password.com/profile', security: 'https://my.1password.com/profile/security' },
    'lastpass': { name: 'LastPass', login: 'https://lastpass.com/misc_login2.php', settings: 'https://lastpass.com/account_settings.php', security: 'https://lastpass.com/account_settings.php' },
    'bitwarden': { name: 'Bitwarden', login: 'https://vault.bitwarden.com/', settings: 'https://vault.bitwarden.com/#/settings', security: null },
    'dashlane': { name: 'Dashlane', login: 'https://app.dashlane.com/', settings: 'https://app.dashlane.com/my-account', security: null },
    'keeper': { name: 'Keeper', login: 'https://keepersecurity.com/vault/', settings: 'https://keepersecurity.com/vault/', security: null },
    'nordpass': { name: 'NordPass', login: 'https://app.nordpass.com/login', settings: 'https://app.nordpass.com/settings', security: null },
    'proton': { name: 'Proton', login: 'https://account.proton.me/login', settings: 'https://account.proton.me/', security: 'https://account.proton.me/security' },
    'protonmail': { name: 'ProtonMail', login: 'https://mail.proton.me/', settings: 'https://account.proton.me/', security: 'https://account.proton.me/security' },
    'tutanota': { name: 'Tutanota', login: 'https://mail.tutanota.com/', settings: 'https://mail.tutanota.com/settings', security: null },
    'fastmail': { name: 'Fastmail', login: 'https://www.fastmail.com/login/', settings: 'https://www.fastmail.com/settings/', security: 'https://www.fastmail.com/settings/security/' },
    'zoho': { name: 'Zoho', login: 'https://accounts.zoho.com/signin', settings: 'https://accounts.zoho.com/home', security: 'https://accounts.zoho.com/home#security/security_settings' },
    'atlassian': { name: 'Atlassian', login: 'https://id.atlassian.com/login', settings: 'https://id.atlassian.com/manage-profile', security: 'https://id.atlassian.com/manage-profile/security' },
    'wordpress': { name: 'WordPress.com', login: 'https://wordpress.com/log-in', settings: 'https://wordpress.com/me', security: 'https://wordpress.com/me/security' },
    'wix': { name: 'Wix', login: 'https://users.wix.com/signin', settings: 'https://users.wix.com/account/settings', security: 'https://users.wix.com/account/settings' },
    'squarespace': { name: 'Squarespace', login: 'https://login.squarespace.com/', settings: 'https://account.squarespace.com/settings', security: 'https://account.squarespace.com/settings/security' },
    'webflow': { name: 'Webflow', login: 'https://webflow.com/login', settings: 'https://webflow.com/dashboard/account/general', security: 'https://webflow.com/dashboard/account/login-and-security' },
    'ghost': { name: 'Ghost', login: 'https://ghost.org/signin/', settings: 'https://ghost.org/settings/', security: 'https://ghost.org/settings/account' },
    'substack': { name: 'Substack', login: 'https://substack.com/sign-in', settings: 'https://substack.com/settings', security: null },
    'patreon': { name: 'Patreon', login: 'https://www.patreon.com/login', settings: 'https://www.patreon.com/settings/profile', security: 'https://www.patreon.com/settings/account' },
    'kofi': { name: 'Ko-fi', login: 'https://ko-fi.com/account/login', settings: 'https://ko-fi.com/Manage/Account', security: null },
    'buymeacoffee': { name: 'Buy Me a Coffee', login: 'https://www.buymeacoffee.com/login', settings: 'https://www.buymeacoffee.com/settings', security: null },
    'gumroad': { name: 'Gumroad', login: 'https://app.gumroad.com/login', settings: 'https://app.gumroad.com/settings', security: null },
    'teachable': { name: 'Teachable', login: 'https://sso.teachable.com/secure/login', settings: 'https://sso.teachable.com/secure/account', security: null },
    'thinkific': { name: 'Thinkific', login: 'https://app.thinkific.com/users/sign_in', settings: 'https://app.thinkific.com/manage/account', security: null },
    'podia': { name: 'Podia', login: 'https://app.podia.com/login', settings: 'https://app.podia.com/settings', security: null },
    'kajabi': { name: 'Kajabi', login: 'https://app.kajabi.com/login', settings: 'https://app.kajabi.com/admin/account', security: null },
};
